// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/19/2026, 9:34:24 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/plugins/**/*.{js,ts,mjs}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/composables/**/*.{js,ts,mjs}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/composables/**/**/*.{js,ts,mjs}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/utils/**/*.{js,ts,mjs}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/utils/**/**/*.{js,ts,mjs}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/app.config.{js,ts,mjs}","/home/dungdao/Documents/development_ai/company_system/compliance-system-fe/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;