export const HEADER_TABLE = [
  { key: "no", label: "text.stt", sortable: false, minWidth: "60px" },
  { key: "code", label: "employee.code", minWidth: "120px", sortable: true },
  { key: "full_name", label: "employee.fullName", minWidth: "200px", sortable: true },
  { key: "email", label: "employee.email", minWidth: "220px", sortable: true },
  { key: "phone", label: "employee.phone", minWidth: "150px" },
  { key: "role", label: "employee.role", minWidth: "120px" },
  { key: "status", label: "employee.status", minWidth: "120px" },
  { key: "action", label: "", frozen: true },
];
export const FIELD_VALIDATIONS = {
  // Tab 0
  full_name: { transitionKey: "employee.fullName", types: ["require", "max150"], errorKey: "errorFullName" },
  full_name_kana: { transitionKey: "employee.katakanaName", types: ["max150"], errorKey: "errorFullNameKana" },
  romaji_name: { transitionKey: "employee.romajiName", types: ["max150"], errorKey: "errorRomajiName" },
  date_of_birth: { transitionKey: "employee.dateOfBirth", types: [], errorKey: "errorDateOfBirth" },
  gender: { transitionKey: "employee.gender", types: [], errorKey: "errorGender" },
  hometown: { transitionKey: "employee.hometown", types: ["max255"], errorKey: "errorHometown" },
  place_of_birth: { transitionKey: "employee.placeOfBirth", types: ["max255"], errorKey: "errorPlaceOfBirth" },
  nationality: { transitionKey: "employee.nationality", types: ["max100"], errorKey: "errorNationality" },
  ethnicity: { transitionKey: "employee.ethnicity", types: ["max100"], errorKey: "errorEthnicity" },
  religion: { transitionKey: "employee.religion", types: ["max100"], errorKey: "errorReligion" },
  email: { transitionKey: "employee.email", types: ["require", "validEmail", "max150"], errorKey: "errorEmail" },
  phone: { transitionKey: "employee.phone", types: ["require", "max20"], errorKey: "errorPhone" },
  password: { transitionKey: "employee.password", types: ["minLength8", "max50"], errorKey: "errorPassword" }, // Checked dynamically if create
  department_id: { transitionKey: "employee.department", types: ["require"], errorKey: "errorDepartmentId" },
  job_title_id: { transitionKey: "employee.jobTitle", types: ["require"], errorKey: "errorJobTitleId" },
  join_date: { transitionKey: "employee.joinDate", types: ["require"], errorKey: "errorJoinDate" },

  // Tab 1
  identity_number: { transitionKey: "employee.identityNumber", types: ["max50"], errorKey: "errorIdentityNumber" },
  tax_code: { transitionKey: "employee.taxCode", types: ["max50"], errorKey: "errorTaxCode" },
  social_insurance_code: { transitionKey: "employee.socialInsurance", types: ["max50"], errorKey: "errorSocialInsuranceCode" },
  pension_number: { transitionKey: "employee.pensionNumber", types: ["max50"], errorKey: "errorPensionNumber" },
  employment_insurance_number: { transitionKey: "employee.employmentInsurance", types: ["max50"], errorKey: "errorEmploymentInsuranceNumber" },
  address_registered: { transitionKey: "employee.registeredAddress", types: ["max500"], errorKey: "errorAddressRegistered" },
  address_current: { transitionKey: "employee.currentAddress", types: ["max500"], errorKey: "errorAddressCurrent" },

  // Tab 2
  bank_code: { transitionKey: "employee.bankCode", types: ["max10"], errorKey: "errorBankCode" },
  bank_branch_code: { transitionKey: "employee.bankBranch", types: ["max10"], errorKey: "errorBankBranchCode" },
  bank_account_type: { transitionKey: "employee.bankAccountType", types: ["max50"], errorKey: "errorBankAccountType" },
  bank_account_number: { transitionKey: "employee.bankAccountNumber", types: ["max50"], errorKey: "errorBankAccountNumber" },
  bank_account_holder_kana: { transitionKey: "employee.bankAccountHolder", types: ["max150"], errorKey: "errorBankAccountHolderKana" },
};

export const DEFAULT_FORM = {
  avatar: '',
  full_name: '',
  full_name_kana: '',
  romaji_name: '',
  date_of_birth: null,
  gender: 'MALE',
  hometown: '',
  place_of_birth: '',
  nationality: 'Việt Nam',
  ethnicity: 'Kinh',
  religion: 'Không',
  email: '',
  phone: '',
  password: '',
  department_id: null,
  job_title_id: null,
  join_date: null,
  role: 'STAFF',
  status: 'PROBATION',
  identity_type: 'CCCD',
  identity_number: '',
  zairyu_card_expiry: null,
  tax_code: '',
  social_insurance_code: '',
  pension_number: '',
  employment_insurance_number: '',
  bank_code: '',
  bank_branch_code: '',
  bank_account_type: '',
  bank_account_number: '',
  bank_account_holder_kana: '',
  address_registered: '',
  address_current: '',
  relatives: [],
  relativeErrors: [],
  work_histories: [],
  workHistoryErrors: [],

  // Realtime Validation Errors
  errorFullName: '',
  errorFullNameKana: '',
  errorRomajiName: '',
  errorDateOfBirth: '',
  errorGender: '',
  errorHometown: '',
  errorPlaceOfBirth: '',
  errorNationality: '',
  errorEthnicity: '',
  errorReligion: '',
  errorEmail: '',
  errorPhone: '',
  errorPassword: '',
  errorDepartmentId: '',
  errorJobTitleId: '',
  errorJoinDate: '',
  errorIdentityNumber: '',
  errorTaxCode: '',
  errorSocialInsuranceCode: '',
  errorPensionNumber: '',
  errorEmploymentInsuranceNumber: '',
  errorAddressRegistered: '',
  errorAddressCurrent: '',
  errorBankCode: '',
  errorBankBranchCode: '',
  errorBankAccountType: '',
  errorBankAccountNumber: '',
  errorBankAccountHolderKana: ''
};
